# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd2cb4b135ff74d840dccf65d926a8cf4c35cdce74b54c46f5ea501a86eb7495dfa1ec512a10d6bf99dad31f292e86bb3af68fc80b87e30fbb6a81a41dcddcc

test:
  secret_key_base: 77d177013b516a6c1e05264e8b87f5e7b3ff0b2a059623efa44cdf609170d06c8afdd3d83ebf715705f49b800f47f6ad92e107d20bfa57df933eea4012744756

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
